apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fpnf875p0-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fpnf875p0-python 
  name: fpnf875p0-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fpnf875p0-python 
